stages:
- stage: API_Tests
  jobs:
  - job: API_Testing
    steps:
    - script: # Commands to run API tests

- stage: UI_Tests
  jobs:
  - job: UI_Testing
    steps:
    - script: # Commands to run UI tests
      displayName: Run UI tests
    - task: PublishTestResults@2 # Publish test results
    - task: PublishBuildArtifacts@1 # Publish screenshots as artifacts
      displayName: Publish Screenshots

- stage: Manual
  jobs:
  - job: Manual_Trigger
    steps:
    - task: PublishBuildArtifacts@1
    - script: # Commands to run both API and UI tests
      displayName: Run API and UI tests

    # Even if API tests fail, UI tests will still run because they are in a separate stage
    - task: PublishTestResults@2 # Publish test results
    - task: PublishBuildArtifacts@1 # Publish screenshots as artifacts
      displayName: Publish Screenshots